version: 2

formats: all

build:
  image: latest
  tools:
    python: "3.11"
  apt_packages:
    - "plantuml"

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py
