---
name: Bug Report
description: Bug Report
title: "bug: "
labels: ["bug"]
assignees:
  - attilasomogyi

body:
  - type: dropdown
    id: component
    attributes:
      label: Effected component
      description: Effected component
      multiple: true
      options:
        - plantuml-settings.puml
        - examples
        - changelog
        - readme
        - docs
        - conf.py
        - makefile
        - js
        - css
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: Effected version
      description: Effected version
      multiple: false
      options:
        - "v1.8.4"
    validations:
      required: true

  - type: dropdown
    id: severity-level
    attributes:
      label: Severity level
      description: Severity level
      multiple: false
      options:
        - "s1: critical"
        - "s2: major"
        - "s3: minor/moderate"
        - "s4: low"
    validations:
      required: true

  - type: dropdown
    id: priority-level
    attributes:
      label: Priority level
      description: Priority level
      multiple: false
      options:
        - "p1: immediate/critical"
        - "p2: high"
        - "p3: medium"
        - "p4: low"
    validations:
      required: true
